name: Octopress Deploy
on: [workflow_dispatch]
jobs:
  deploy-site: 
    runs-on: macos-latest
    steps:
    # You may pin to the exact commit or the version.
    # uses: rcmdnk/octopress-action@6d69d29a038429e62ab38ee06d9f2bd64de49b8e
    - uses: rcmdnk/octopress-action@v3.0.0
      with:
        # ssh key for the deployment
        ssh_key: ${{ secrets.SSH_KEY }}
        # Git user email
        git_user_email: jivimberg@gmail.com
        # Git user name
        git_user_name: jivimberg
