name: 'Octopress Deploy Action'
on: [workflow_dispatch]

jobs:
  deploy-site:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7.2'
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - uses: gabrielfalcao/pyenv-action@v11
        with:
          default: 2.7.18
      - run: .github/scripts/octopress-deploy.sh "${{secrets.OCTOPRESS_DEPLOY_SSH_KEY}}" "jivimberg@gmail.com" "jivimberg"
        shell: bash
