name: 'Octopress Deploy Action'
on: [workflow_dispatch]

jobs:
  deploy-site:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - run: .github/scripts/octopress-deploy.sh "${{inputs.ssh_key}}" "jivimberg@gmail.com" "jivimberg"
        shell: bash
